# -*- coding: utf-8 -*-
"""COURT_RESERVATION

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SprncjKztJ6ylUXWcX1Gsbd7LuhmPkYD
"""

"""

UWAGA! ATTENTION! PROJECT WORKS ONLY FOR ONE COURT NOW!!!!! PLEASE, USE COURT = 1 

"""

import typing
import dataclasses
import datetime
import sqlite3 #library of SQLLite
import csv
import json

"""

Class Booking for booking slot. Definition of reservation data format

"""

@dataclasses.dataclass
class Booking:
  court : int
  slot : int
  name : str
  surname : str
  reservation_data : str
  
  
  def reservation_data(self, year, month, day, hour, minute):
    d = datetime.datetime(year, month, day, hour, minute)
    self.reservation_data = d.strftime("%Y-%m-%d %H:%M")

"""

Class for SQL operations

"""


class SQLiteDB:
    def __init__(self, db_name):
        self.db_name = db_name
        self.conn = sqlite3.connect(db_name)
        self.cursor = self.conn.cursor()

    def create_table(self, table_name, columns):
        self.conn = sqlite3.connect(self.db_name)
        query = f"CREATE TABLE IF NOT EXISTS {table_name} ({columns})"
        self.cursor.execute(query)
        self.conn.commit()
        self.closing()
    
    def insert_reservation(self, booking:Booking):
        self.conn = sqlite3.connect(self.db_name)
        self.cursor.execute('INSERT INTO reservations (court,slot,name,surname,date) VALUES (?, ?, ?, ?, ?)', (booking.court,booking.slot,booking.name,booking.surname,booking.reservation_data))
        self.conn.commit()
        self.closing()
    
    def closing(self):
        self.conn.close()
    
    def delete_reservation(self,name,surname,date):
        self.conn = sqlite3.connect(self.db_name)
        query = f"DELETE FROM reservations WHERE name = \"{name}\" AND surname = \"{surname}\" AND date = \"{date}\""
        self.cursor.execute(query)
        self.conn.commit()
        self.closing()

    def count_reservation(self,name,week_res,reservation_data):
        self.conn = sqlite3.connect(self.db_name)
        query = f"SELECT COUNT(*) FROM reservations WHERE name=? AND date BETWEEN ? AND ?"
        self.cursor.execute(query,(name, week_res,reservation_data))
        res_this_week = self.cursor.fetchone()[0]
        self.closing()
        return res_this_week
    
    def show_table(self):
        self.conn = sqlite3.connect(self.db_name)
        query = f"SELECT * FROM reservations"
        self.cursor.execute(query)
        print(self.cursor.fetchall())
        self.closing()

    def reservation_exists(self,name,surname,reservation_data) :
        self.conn = sqlite3.connect(self.db_name)
        query = f"SELECT * FROM reservations WHERE name=? AND surname=? AND date=?"
        self.cursor.execute(query,(name,surname,reservation_data))
        self.closing()
        return self.cursor.fetchone()

    def get_reservations_in_time(self,res_this_time,reservation_data):
           
        self.conn = sqlite3.connect(self.db_name)
        query = f"SELECT date FROM reservations WHERE date BETWEEN ? AND ?"
        self.cursor.execute(query,(res_this_time,reservation_data))
        output = self.cursor.fetchall()
        self.closing()
        return output
    
    def get_slot_in_time(self,res_this_time,reservation_data):
        self.conn = sqlite3.connect(self.db_name)
        query = f"SELECT date,slot FROM reservations WHERE date BETWEEN ? AND ?"
        self.cursor.execute(query,(res_this_time,reservation_data))
        output = self.cursor.fetchall()
        self.closing()
        return output


    def print_sheduel(self,start_date,end_date):
        self.conn = sqlite3.connect(self.db_name)
        query = f"SELECT name, surname, date, slot FROM reservations WHERE date BETWEEN ? AND ? ORDER BY date"
        self.cursor.execute(query,(start_date,end_date))
        return self.cursor.fetchall()

"""

Creating of db

"""

sql_api = SQLiteDB('reservations.db')
sql_api.create_table('reservations', 'court TEXT, slot TEXT, name TEXT, surname TEXT, date TEXT')

"""

Test input data for insert. 

"""

booking = Booking(1,30,"a","n","2024-04-05 14:00")
sql_api.insert_reservation(booking)
booking = Booking(1,30,"a","n","2024-04-05 14:30")
sql_api.insert_reservation(booking)
booking = Booking(1,30,"a","n","2024-04-05 15:00")
sql_api.insert_reservation(booking)
booking = Booking(1,30,"a","n","2024-04-05 15:30")
sql_api.insert_reservation(booking)
booking = Booking(1,30,"a","n","2024-04-05 17:30")
sql_api.insert_reservation(booking)
booking = Booking(1,30,"a","n","2024-04-05 18:00")
sql_api.insert_reservation(booking)
# sql_api.delete_reservation("a","n","abc")

"""

Test delete 

"""

sql_api.delete_reservation("a","n","2024-04-05 14:00")

"""

Show of SQL database

"""

sql_api.show_table()

"""

Globals

"""


MAX_RESERVATIONS = 2
HOURS_BOOKING = 1

"""

Check if not two reservations per week

"""


def two_res_check(booking):
  reservation_object = datetime.datetime.strptime(booking.reservation_data, '%Y-%m-%d %H:%M')
  week_res = reservation_object - datetime.timedelta(days=7)
  
  res_this_week = sql_api.count_reservation(booking.name,week_res,booking.reservation_data)

  if res_this_week >= MAX_RESERVATIONS:
    print("Sorry limit of reservations for this week")
    return False
  return True

"""

Checking if booking in advance

"""


def checking_of_data(booking):
  reservation_object = datetime.datetime.strptime(booking.reservation_data, '%Y-%m-%d %H:%M')
  if reservation_object < datetime.datetime.now() + datetime.timedelta(hours=HOURS_BOOKING):
    print("Sorry, you should book slot at least one hour in advance")
    return False

  return True

"""

Check options of time slots to choose


"""


def court_av(booking):
  reservation_object = datetime.datetime.strptime(booking.reservation_data, '%Y-%m-%d %H:%M')
  res_this_time = reservation_object + datetime.timedelta(hours=1, minutes=30)
  time_data = sql_api.get_reservations_in_time(booking.reservation_data, res_this_time)

  if len(time_data)==0:
    return 3
  nearest_reservation = min(time_data,key=lambda x:datetime.datetime.strptime(x[0], '%Y-%m-%d %H:%M')-reservation_object)
  free_time = datetime.datetime.strptime(nearest_reservation[0],'%Y-%m-%d %H:%M') -reservation_object
  minutes = int(free_time.total_seconds()/60)
  if minutes < 30:
    return 0
  if minutes < 60:
    return 1
  else:
    return 2

"""

Check if reservation is not during game of other person

"""
def court_ava_2(booking):
  reservation_object = datetime.datetime.strptime(booking.reservation_data, '%Y-%m-%d %H:%M')
  res_this_time = reservation_object - datetime.timedelta(hours=1, minutes=30)
  time_data = sql_api.get_slot_in_time(res_this_time, booking.reservation_data)
  for start_time, slot in time_data:
    #time_game_list.append(time_of_game(start_time, int(slot)))
    duration = time_of_game(start_time, int(slot))
    if time_av(duration, reservation_object):
      return False
  return True

"""

Functions for court_ava_2

"""
def time_of_game(start_time, slot):
  start_time = datetime.datetime.strptime(start_time, '%Y-%m-%d %H:%M')
  minutes_of_game = datetime.timedelta(minutes=slot)
  return start_time, start_time+minutes_of_game

def time_av(duration, reservation):
  start, end = duration
  if start <= reservation < end:
    return True
  return False

"""

Checking is reservation exists

"""


def reservation_exists(booking):
  return sql_api.reservation_exists(booking.name, booking.surname, booking.reservation_data) is not None

"""

Printing schedule

"""


def print_schedule(start_date, end_date):
  reservations = sql_api.print_sheduel(start_date, end_date)
  if len(reservations)==0:
    print("No reservation for such data")
  else:
    for name,surname,start_time,slot in reservations:
      duration = time_of_game(start_time, int(slot))
      start, end = duration

      print(name, surname, start, ' - ', end)

"""

Saving schedule in format 


"""


def save_schedule(start_date, end_date, file_format, file_name):
  reservations = sql_api.print_sheduel(start_date, end_date)

  if file_format == "csv":
    with open(file_name+".csv", mode='w', newline='') as file:
      writer = csv.writer(file)
      writer.writerow(["Name", "Start_Time", "End_Time" ])
      for name,surname,start_time,slot in reservations:
        person = f"{name} {surname}"
        duration = time_of_game(start_time, int(slot))
        start, end = duration
        writer.writerow([person, start, end])

  elif file_format == "json":
    with open(file_name+".json", mode='w', newline='') as file:
      end_date = datetime.datetime.strptime(end_date, '%Y-%m-%d %H:%M')
      start_date = datetime.datetime.strptime(start_date, '%Y-%m-%d %H:%M')

      delta = end_date - start_date

      #end_date = str(end_date.year) + '-' + str(end_date.month) + '-' + str(end_date.day)
      #start_date = str(start_date.year) + '-' + str(start_date.month) + '-' + str(start_date.day)
      
      my_reservations = {}
      for i in range(delta.days + 1):
        date = start_date + datetime.timedelta(days=i)
        date_name = str(date.year) + '-' + str(date.month) + '-' + str(date.day)
        my_reservations[f'{date_name}'] = []

      for name,surname,start_time,slot in reservations:

        person = f"{name} {surname}"
        duration = time_of_game(start_time, int(slot))
        start, end = duration
        reservation_dict = {
                  "name": person,
                  "start_time": str(start),
                  "end_time": str(end)
              }
        date_name = str(start.year) + '-' + str(start.month) + '-' + str(start.day)
        my_reservations[f'{date_name}'].append(reservation_dict)
        json_object = json.dumps(my_reservations)
        file.write(json_object)
    print(my_reservations)

"""

Main function for booking

"""


def Home():
  while(True):

    print("\n\t\t\t\t\t\t WELCOME TO COURT BOOKING\n")
    print("\t\t\t 1 Booking\n")
    print("\t\t\t 2 Reservation information\n")
    print("\t\t\t 3 Cancelling reservation\n")
    print("\t\t\t 4 Exit\n")
    ch=int(input("->"))

    if ch == 1:
      print("Court booking")
      court = int(input("Write court: "))
      name = str(input("Write name: "))
      surname = str(input("Write surname: "))
      reservation_data = str(input("Write the reservation date and time in format YYYY-MM-DD HH:MM"))
      booking = Booking(court,0,name,surname,reservation_data)
      max_time = court_av(booking)
      print
      court_is_free = court_ava_2(booking)
      print("How long would you like to book court?")
      
      if not court_is_free:
        print('Reservation is not available. Sorry')
        continue 

      if max_time == 0:
        print("No booking available!")
      elif max_time == 1:
        print("1)30 Minutes")
      elif max_time == 2:
        print("1)30 Minutes")
        print("2)60 Minutes")
      else:
        print("1)30 Minutes")
        print("2)60 Minutes")
        print("3)90 Minutes")

      slot = int(input())
      if slot > max_time:
        print("Incorrect timeslot!")
        continue
      if slot == 1:
        slot = 30
      elif slot == 2:
        slot = 60
      elif slot == 3:
        slot = 90
      else:
        print("Unsupported input")
        continue
  
      booking = Booking(court,slot,name,surname,reservation_data)

      if checking_of_data(booking) and two_res_check(booking):
        sql_api.insert_reservation(booking)
      else:
        print("Unfortunately,reservation is invalid ")

      
    elif ch == 2:
      print("Shedule")
      start_date = str(input("Write the start date and time in format YYYY-MM-DD HH:MM: "))
      end_date = str(input("Write the end date and time in format YYYY-MM-DD HH:MM: "))
      print_schedule(start_date, end_date)
      print("Do you want to print shedule?")
      print("1)Yes")
      print("2)No")
      answer = int(input())
      if answer == 1:
        print("In which format?")
        print("1)CSV")
        print("2)JSON")
        format = int(input())
        if format == 1:
          file_name = str(input("Write filename: "))
          save_schedule(start_date, end_date, "csv", file_name)
        elif format == 2:
          file_name = str(input("Write filename: "))
          save_schedule(start_date, end_date, "json", file_name)
        else:
          print("Unsupported input")
          continue

      elif answer == 2:
        break

      else:
        print("Unsupported input")
        continue
    elif ch == 3:
      print("Cancellation of reservation")
      name = str(input("Write name: "))
      surname = str(input("Write surname: "))
      reservation_data = str(input("Write the reservation date and time in format YYYY-MM-DD HH:MM"))
      booking = Booking(0,0,name,surname,reservation_data)
      if reservation_exists(booking) and checking_of_data(booking):
        sql_api.delete_reservation(name,surname,reservation_data)
        print("Deleted successfully")
      else:
        print("This booking doesn't exist")
    elif ch == 4:
      break  
    else:
      print("Unknown")

"""

Function calling

"""
Home()

#2024-04-05 15:00